name:                ynab-transaction-differ
version:             0.1.0.0
github:              "fullstackgjj/ynab-transaction-differ"
license:             BSD3
author:              "Hank Lin"
maintainer:          "fullstackgjj@gmail.com"
copyright:           "2021 Hank Lin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ynab-transaction-differ#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - bytestring
  - containers
  - lens
  - lens-aeson
  - split
  - text
  - wreq

executables:
  ynab-transaction-differ-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ynab-transaction-differ
    when:
    - condition: false
      other-modules: Paths_ynab_transaction_differ

tests:
  ynab-transaction-differ-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ynab-transaction-differ
    - HUnit
    - hspec
    - containers
