name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: '8.10.2'
          cabal-version: '3.2'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: store-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('ynab-transaction-differ.cabal') }}

      - name: Build
        run: stack build

      - name: Run tests
        run: stack test
